package com.app.desktop.buruhpabrik.timbanganpacking.model;
// Generated Nov 28, 2016 3:37:48 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * BpMasterpacking generated by hbm2java
 */
public class BpMasterpacking  implements java.io.Serializable {


     private Integer id;
     private String materialNo;
     private String warna;
     private String batch;
     private BigDecimal tara;
     private BigDecimal taraCones;
     private Date tanggal;
     private BpStandar bpStandar;
     private int hapus;
     private Integer createdBy;
     private Integer updatedBy;
     private Date createDate;
     private Date updateDate;

    public BpMasterpacking() {
    }

	
    public BpMasterpacking(String materialNo, String batch, Date tanggal, BpStandar bpStandar, int hapus) {
        this.materialNo = materialNo;
        this.batch = batch;
        this.tanggal = tanggal;
        this.bpStandar = bpStandar;
        this.hapus = hapus;
    }
    public BpMasterpacking(String materialNo, String warna, String batch, BigDecimal tara, BigDecimal taraCones, Date tanggal, BpStandar bpStandar, int hapus, Integer createdBy, Integer updatedBy, Date createDate, Date updateDate) {
       this.materialNo = materialNo;
       this.warna = warna;
       this.batch = batch;
       this.tara = tara;
       this.taraCones = taraCones;
       this.tanggal = tanggal;
       this.bpStandar = bpStandar;
       this.hapus = hapus;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.createDate = createDate;
       this.updateDate = updateDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMaterialNo() {
        return this.materialNo;
    }
    
    public void setMaterialNo(String materialNo) {
        this.materialNo = materialNo;
    }
    public String getWarna() {
        return this.warna;
    }
    
    public void setWarna(String warna) {
        this.warna = warna;
    }
    public String getBatch() {
        return this.batch;
    }
    
    public void setBatch(String batch) {
        this.batch = batch;
    }
    public BigDecimal getTara() {
        return this.tara;
    }
    
    public void setTara(BigDecimal tara) {
        this.tara = tara;
    }
    public BigDecimal getTaraCones() {
        return this.taraCones;
    }
    
    public void setTaraCones(BigDecimal taraCones) {
        this.taraCones = taraCones;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    } 
    public BpStandar getBpStandar() {
        return bpStandar;
    }

    public void setBpStandar(BpStandar bpStandar) {
        this.bpStandar = bpStandar;
    }
    public int getHapus() {
        return this.hapus;
    }
    
    public void setHapus(int hapus) {
        this.hapus = hapus;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


