package com.app.desktop.buruhpabrik.timbanganpacking.model;
// Generated Nov 28, 2016 3:37:48 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * BpTimbangan generated by hbm2java
 */
public class BpTimbangan  implements java.io.Serializable {


     private Integer id;
     private Date tanggal;
     private Integer mill;
     private String urutNo;
     private BigDecimal berat;
     private BigDecimal beratPapan;
     private Integer pallete;
     private BigDecimal jumlahCones;
     private BigDecimal newpack;
     private int hapus;
     private Integer createdBy;
     private Integer updatedBy;
     private Date createDate;
     private Date updateDate;

    public BpTimbangan() {
    }

	
    public BpTimbangan(int hapus) {
        this.hapus = hapus;
    }
    public BpTimbangan(Date tanggal, Integer mill, String urutNo, BigDecimal berat, BigDecimal beratPapan, Integer pallete, BigDecimal jumlahCones, BigDecimal newpack, int hapus, Integer createdBy, Integer updatedBy, Date createDate, Date updateDate) {
       this.tanggal = tanggal;
       this.mill = mill;
       this.urutNo = urutNo;
       this.berat = berat;
       this.beratPapan = beratPapan;
       this.pallete = pallete;
       this.jumlahCones = jumlahCones;
       this.newpack = newpack;
       this.hapus = hapus;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.createDate = createDate;
       this.updateDate = updateDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public Integer getMill() {
        return this.mill;
    }
    
    public void setMill(Integer mill) {
        this.mill = mill;
    }
    public String getUrutNo() {
        return this.urutNo;
    }
    
    public void setUrutNo(String urutNo) {
        this.urutNo = urutNo;
    }
    public BigDecimal getBerat() {
        return this.berat;
    }
    
    public void setBerat(BigDecimal berat) {
        this.berat = berat;
    }
    public BigDecimal getBeratPapan() {
        return this.beratPapan;
    }
    
    public void setBeratPapan(BigDecimal beratPapan) {
        this.beratPapan = beratPapan;
    }
    public Integer getPallete() {
        return this.pallete;
    }
    
    public void setPallete(Integer pallete) {
        this.pallete = pallete;
    }
    public BigDecimal getJumlahCones() {
        return this.jumlahCones;
    }
    
    public void setJumlahCones(BigDecimal jumlahCones) {
        this.jumlahCones = jumlahCones;
    }
    public BigDecimal getNewpack() {
        return this.newpack;
    }
    
    public void setNewpack(BigDecimal newpack) {
        this.newpack = newpack;
    }
    public int getHapus() {
        return this.hapus;
    }
    
    public void setHapus(int hapus) {
        this.hapus = hapus;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


